### ISSUE TITLE
Socket permission denied DragaonBoard820

### ISSUE THREAD

**Issue by Madan1993** [96boards/meta-96boards#160]
I am not able to ping, error:socket: Permission denied

**Comment by ndechesne** [comment]
I believe this is related to this issue: https://bugs.96boards.org/show_bug.cgi?id=206

are you trying this command as root or standard user?

**Comment by Madan1993** [comment]
yes i am trying with root user, i connected USB Ethernet , got an ip address. while ping :socket permission denied error occur. But ssh connection working fine.
i checked the above link and try to do, following are error log:

root@linaro-developer:~# apt-get install --reinstall iputils-ping
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Reinstallation of iputils-ping is not possible, it cannot be downloaded.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ndechesne** [comment]
hmm. this bug happens if you run with standard user, not root. are you sure you are running as root when running the ping command?

**Comment by Madan1993** [comment]
following is log while sudo user:

root@linaro-developer:~# sudo setcap cap_net_raw+ep /bin/ping                                                                                  
root@linaro-developer:~# sudo getcap /bin/ping
/bin/ping = cap_net_raw+ep
root@linaro-developer:~# sudo ping www.google.com                                                                              
ping: www.google.com: Temporary failure in name resolution

**Comment by Madan1993** [comment]
root@linaro-developer:~# sudo ping 192.168.13.110
socket: Permission denied

Note: 192.168.13.110 is my local host machine

**Comment by ndechesne** [comment]
this is confusing.. 'sudo' is not a user. running sudo when you are already root is not needed.

based on the getcap output , the permissions are correct. so this is not the same issue as in the bugzilla i linked.

**Comment by Madan1993** [comment]
if ping without sudo i.e. 
root@linaro-developer:~# ping 192.168.13.110
same error is coming
socket: Permission denied

 is there need of any modification in file sys or kernel???

**Comment by ndechesne** [comment]
by the way, which kernel version/branch are you running?  any chance you could be running an Android kernel? Android typically has CONFIG_ANDROID_PARANOID_NETWORK to better control who can access network.

**Comment by koenkooi** [comment]
Dragonboard820 machine is in meta-qcom, not meta-96boards, closing.
