### ISSUE TITLE
question regarding optee-client.bb

### ISSUE THREAD

**Issue by vchong** [96boards/meta-96boards#28]
For optee-client.bb, is `PACKAGE_ARCH = "${MACHINE_ARCH}"` needed? Both optee-os_git.bb and optee-test_git.bb have it. Without it, optee_client build files go to `build-rpb-wayland/tmp-rpb_wayland-glibc/aarch64-oe-linux` instead of `build-rpb-wayland/tmp-rpb_wayland-glibc/hikey-oe-linux`, where both optee_os and optee_test are located.

**Comment by koenkooi** [comment]
optee-client reuses files from optee-os, so it needs to be machine specific as well.

**Comment by vchong** [comment]
Sorry if I wasn't clear. 'Needs to be machine specific as well' means `PACKAGE_ARCH = "${MACHINE_ARCH}"` is needed, yes? If yes, then optee-client.bb is missing it.
