### ISSUE TITLE
hisi-idt and ptable aren't shipped

### ISSUE THREAD

**Issue by fboudra** [96boards/meta-96boards#52]
the python script to flash the board in recovery mode and the partition tables aren't shipped.

It isn't a big deal, we can use pre-built one from other builds but it will be better for end users to get everything in a single place.

**Comment by fboudra** [comment]
Missing ptable issue is fixed with https://github.com/96boards/meta-96boards/pull/57

hisi-idt.py script will require a new recipe but it's trivial.

**Comment by fboudra** [comment]
ptable fixed with https://github.com/96boards/meta-96boards/commit/1b6e5299e1f93cc83af0efd4a6c5d7e413133dec

**Comment by koenkooi** [comment]
#60 should fix the missing hisi-idt.py

**Comment by fboudra** [comment]
hisi-idt fixed with https://github.com/96boards/meta-96boards/commit/dde9e4609025d2d964e4e18fbfe32066ec647626
