### ISSUE TITLE
the kernel 4.4's hdmi is not working 

### ISSUE THREAD

**Issue by chengtian61** [96boards/meta-96boards#72]
I have boot up this recipe in hikey, but the HDMI is not working ,I have changed several Display, but still not work, I find the dmesg
732471] [drm:drm_sysfs_connector_add] _ERROR_ failed to register connector device: -2
[    1.814349] hi6210-hdmi-audio 0.hi6210_hdmi_card: ASoC: CPU DAI f7118000.hi6210_i2s not registered
[    1.823408] hi6210-hdmi-audio 0.hi6210_hdmi_card: snd_soc_register_card failed (-517)
[    1.964030] wlcore: ERROR could not get configuration binary ti-connectivity/wl18xx-conf.bin: -2

**Comment by koenkooi** [comment]
The kernel has moved to 4.9 now, please open a new bug if the problem persists in that version.
